//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by the tool.
//     Runtime version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and if
//     Regenerate the code and these changes will be lost.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crs.theme.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class for finding localized strings, etc.
    /// </summary>
    // This type is StronglyTypedResourceBuilder
    // Classes through similar ResGen or Visual Studio The tool is automatically generated.
    // To add or remove members, edit .ResX File, then run again ResGen
    // (by /str As a command option), or regenerate VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager Example.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("crs.theme.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Rewrite the current thread's CurrentUICulture Attributes, right
        ///   Perform rewrite using all resource lookups for this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
